config/routes.rb
Rails.application.routes.draw do
  resources :types, only: [:new, :show, :index, :create]
  resources :expenses, only: [:new, :show, :index, :create]
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, format: { with: /[a-zA-Z]/, message: 'Input invalid.' }, length: { maximum: 20 }
  validates :amount, presence: true, format: { with: /\A\d+\z/, message: 'Input invalid.' }

  belongs_to :user, class_name: 'User'
  has_one :type, through: :user, class_name: 'Type', source: :types, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true, format: { with: /[a-zA-Z]/, message: 'Input invalid.' }, length: { maximum: 20 }
  validates :budget, format: { with: /\A\d+\z/, message: 'Input invalid.' }

  has_one_attached :icon, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :expenses, class_name: 'Expense', foreign_key: 'type_id', dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, format: { with: /[a-zA-Z]/ }, length: { minimum: 5, maximum: 20 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true

  has_many :types, class_name: :Type, dependent: :destroy
  has_many :expenses, class_name: :Expense, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  def new
    @expense = Expense.new
    @types = Type.where(user_id: current_user.id).all.map { |typ| [typ.name, typ.id] }
    @types << ['Empty', nil]
  end

  def index
    @expenses = Expense.where(user_id: current_user.id).where.not(type_id: nil)
    @total = @expenses.sum(:amount)
    @expenses = @expenses.sort_by(&:created_at).reverse
  end

  def show
    @expenses = Expense.where(user_id: current_user.id).where(type_id: nil)
    @total = @expenses.sum(:amount)
    @expenses = @expenses.sort_by(&:created_at).reverse
  end

  def create
    @expense = current_user.expenses.build(expense_params)

    respond_to do |format|
      if @expense.save
        if @expense.type_id.nil?
          format.html { redirect_to '/expenses/show', notice: 'expense was successfully created.' }
        else
          format.html { redirect_to "/types/#{@expense.type_id}", notice: 'expense was successfully created.' }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :user_id, :type_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!
  def new
    @type = Type.new
  end

  def index
    @types = Type.where(user_id: current_user.id)
  end

  def show
    @type = Type.find_by(id: params[:id])
    @expenses = @type.expenses.where(user_id: current_user.id)
    @budget = @type.budget
    @total = @expenses.sum(:amount)
    redirect_to root_path if @type.user_id != current_user.id
  end

  def create
    @type = current_user.types.build(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_path, notice: 'type was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def type_params
    params.require(:type).permit(:name, :icon, :budget, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_type_icon(type_id)
    type_name = Type.find_by(id: type_id)
    if type_name.present? && type_name.icon.present?
      image_tag(type_name.icon, class: 'w-1/5 md:w-2/6')
    else
      image_tag('logo.png', class: 'w-1/5 md:w-2/6')
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def get_type_name(type_id)
    type_name = Type.where(id: type_id)
    type_name.first.name
  end
end

app/helpers/types_helper.rb
# rubocop:disable Style/GuardClause

module TypesHelper
  def calculate_budget(budget, total)
    if budget.present?
      left = budget - total
      "Initial Budget #{budget} €. Money Left #{left} €"
    end
  end
end

# rubocop:enable Style/GuardClause

app/views/expenses/index.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column w-75">
        <h1>Total spent</h1>
        <p><%= @total %> €</p>
        <div class="row">
            <% @expenses.each do |exp| %>
                <div class="col-12 col-md-4 col-lg-2">
                    <div class="card">
                        <div class="image">
                            <i><%= get_type_icon(exp.type_id) %></i>
                        </div>
                        <div class="card-inner">
                            <div class="header">
                                <h2><%= exp.name %></h2>
                                <h3><%= link_to get_type_name(exp.type_id), "/types/#{exp.type_id}" %></h3>
                                <h4><%= exp.amount %> €</h4>
                            </div>
                            <div class="content">
                                <p><%= exp.created_at %></p>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <h4><%= link_to 'Add new', new_expense_path, :class => 'btn btn-colorprimary' %></h4>
    </div>
</div>

app/views/expenses/new.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column">
        <h1 class="col-12">New Expense</h1>
        <%= form_with(model: @expense) do |f| %>
            <div class="field">
                <%= f.label :name %>
                <br>
                <%= f.text_field :name %>
            </div>
            
            <div class="field">
                <%= f.label :amount %>
                <br>
                <%= f.number_field :amount %>
            </div>
            <br>
            <div class="field">
                <%= f.label :type_id %>
                <br>
                <%= f.select('type_id', @types, {}) %>
            </div>
            <br>
            <br>
            <div class="actions">
                <%= f.submit 'Submit', :class =>  'form-btn btn btn-colorprimary'%>
            </div>
        <% end %>
    </div>
</div>

app/views/expenses/show.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column w-75">
        <h1>Total spent</h1>
        <p><%= @total %> €</p>
        <div class="row">
            <% @expenses.each do |exp| %>
                <div class="col-12 col-md-4 col-lg-2">
                    <div class="card">
                        <div class="image">
                            <i><%= get_type_icon(exp.type_id) %></i>
                        </div>
                        <div class="card-inner">
                            <div class="header">
                                <h2><%= exp.name %></h2>
                                <h4><%= exp.amount %> €</h4>
                            </div>
                            <div class="content">
                                <p><%= exp.created_at %></p>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <h4><%= link_to 'Add new', new_expense_path, :class => 'btn btn-colorprimary' %></h4>
    </div>
</div>

app/views/home/index.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="mainbody text-center">
            <div class="maintext text-center w-100">
                <h1 class="pt-5"> Welcome <%= current_user.name %>! </h1>
                <p class="pb-2">ExpensesTracker: An easy way to manage your expenses and keep track of your budget! </p>
                <div class="column">
                    <a class="col-12 col-md-3 btn btn-colorprimary m-1" href="/expenses/new">New</a>
                    <a class="col-12 col-md-3 btn btn-colorprimary m-1" href="/expenses">Expenses</a>
                    <a class="col-12 col-md-3 btn btn-colorprimary m-1" href="/expenses/show">External</a>
                    <a class="col-12 col-md-3 btn btn-colorprimary m-1" href="/types">Types</a>
                </div>
            </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>ExpensesTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<nav class="nav-colorprimary">
  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <% if user_signed_in? %>
      <a class="nav-link text-white" href="/expenses/new">Add Expense</a>
      <a class="nav-link text-white" href="/expenses">All Expenses</a>
      <a class="nav-link text-white" href="/expenses/show">All External Expenses</a>
      <a class="nav-link text-white" href="/types">Types</a>
      <a class="nav-link text-white" href="/users/edit"><%= current_user.name %></a>
      <a class="nav-link text-white" href="/users/sign_out">Logout</a>
    <% else %>
      <a class="nav-link text-white" href="/users/sign_up">Sign up</a>
      <a class="nav-link text-white" href="/users/sign_in">Login</a>
    <% end %>
  </div>

  <div class="pl-3 pb-2 pl-md-5">
    <div class="row">
      <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
      <a href="/" class="text-white pt-1"><h2>ExpensesTracker</h2></a>
    </div>
  </div>

  <script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
  }

  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }
  </script>
</nav>
<body>
  <%= yield %>
</body>
</html>

app/views/types/index.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column w-75">
        <h1>All Types</h1>
        <div class="row">
            <% @types.each do |typ| %>
                <div class="col-12 col-md-4 col-lg-2">
                    <div class="card">
                        <div class="image">
                            <i><%= get_type_icon(typ.id) %></i>
                        </div>
                        <div class="card-inner">
                            <div class="header">
                                <h2><%= link_to typ.name, "/types/#{typ.id}" %></h2>
                            </div>
                            <div class="content">
                                <p><%= typ.created_at %></p>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <h4><%= link_to 'Add new', new_type_path, :class => 'btn btn-colorprimary' %></h4>
    </div>
</div>

app/views/types/new.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column">
        <h1 class="col-12">New Type</h1>
        <%= form_with(model: @type) do |f| %>
            <div class="field">
                <%= f.label :name %>
                <br>
                <%= f.text_field :name %>
            </div>
            <div class="field">
                <%= f.label :budget %>
                <br>
                <%= f.number_field :budget %>
            </div>
            <br>
            <br>
            <div>
                <%= f.file_field :icon %>
            </div>
            <br>
            <br>
            <div class="actions">
                <%= f.submit 'Submit', :class =>  'form-btn btn btn-colorprimary'%>
            </div>
        <% end %>
    </div>
</div>

app/views/types/show.html.erb
<div class="w-100 d-flex justify-content-center text-center">
    <div class="column w-75">
        <h1><%= @type.name %></h1>
        <h2>Total spent</h1>
        <h3><%= @total %> €</h3>
        <h5><%= calculate_budget(@budget, @total) %></h5>
        <br>
        <div class="row">
            <% @expenses.each do |exp| %>
                <div class="col-12 col-md-4 col-lg-2">
                    <div class="card">
                        <div class="image">
                            <i><%= get_type_icon(exp.type_id) %></i>
                        </div>
                        <div class="card-inner">
                            <div class="header">
                                <h2><%= exp.name %></h2>
                                <h3><%= get_type_name(exp.type_id) %></h2>
                                <h4><%= exp.amount %> €</h4>
                            </div>
                            <div class="content">
                                <p><%= exp.created_at %></p>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <h4><%= link_to 'Add new', new_expense_path, :class => 'btn btn-colorprimary' %></h4>
    </div>
</div>